#' @include internal.R
#'
#' @title Register an atomic objective (internal)
#'
#' @description
#' Internal helper used by objective setter functions to optionally register an objective
#' as an \emph{atomic objective} for multi-objective workflows.
#'
#' If \code{alias} is non-\code{NULL}, the objective definition is stored in
#' \code{x$data$objectives[[alias]]}. This allows external multi-objective orchestration
#' (e.g., weighted sum, \eqn{\epsilon}-constraint, AUGMECON, interactive methods) to refer to
#' objectives by a stable user-facing identifier.
#'
#' The function is fully backward compatible with single-objective workflows: when
#' \code{alias} is \code{NULL}, no entry is added to \code{x$data$objectives} and only the
#' active single-objective specification stored in \code{x$data$model_args} (set by the calling
#' objective setter) is used.
#'
#' @param x A \code{Problem} object.
#' @param alias Character scalar or \code{NULL}. Unique identifier to register the objective.
#' @param objective_id Character. Stable objective identifier (e.g., \code{"min_cost"}).
#' @param model_type Character. Model type label used by the model builder (e.g., \code{"minimizeCosts"}).
#' @param objective_args List. Objective-specific arguments to be stored with the objective.
#' @param sense Character. Either \code{"min"} or \code{"max"}.
#'
#' @return The updated \code{Problem} object.
#'
#' @keywords internal
#'
#' @title Add objective: minimize costs
#'
#' @description
#' Specify an objective that minimizes total costs associated with the solution.
#' Costs may include planning-unit costs and/or action costs. When `actions` is provided,
#' the action-cost component is restricted to that subset of actions, while planning-unit
#' costs remain global.
#'
#' @param x A `Problem` object.
#' @param include_pu_cost Logical. If `TRUE`, include planning-unit costs.
#' @param include_action_cost Logical. If `TRUE`, include action costs.
#' @param actions Optional subset of actions to include in the action-cost component.
#'   Values may match `actions$id` and, if present, `actions$action_set`.
#' @param alias Optional identifier for multi-objective workflows.
#'
#' @return Updated `Problem` object.
#' @export
add_objective_min_cost <- function(
    x,
    include_pu_cost = TRUE,
    include_action_cost = TRUE,
    actions = NULL,
    alias = NULL
) {
  stopifnot(inherits(x, "Problem"))

  action_subset <- NULL
  if (!is.null(actions)) {
    action_subset <- .pa_resolve_action_subset(x, actions)
  }

  args <- list(
    include_pu_cost = isTRUE(include_pu_cost),
    include_action_cost = isTRUE(include_action_cost),
    actions = if (is.null(action_subset)) NULL else as.character(action_subset$id)
  )

  .pa_set_active_and_register_objective(
    x = x,
    model_type = "minimizeCosts",
    objective_id = "min_cost",
    objective_args = args,
    sense = "min",
    alias = alias
  )
}

#' @title Add objective: maximize benefit
#'
#' @description
#' Specify an objective that maximizes the total positive effects generated by selected
#' actions on selected features.
#'
#' The objective is built from the canonical effects table stored in
#' \code{x$data$dist_effects} and always uses the non-negative \code{benefit} component.
#' In other words, this objective maximizes the positive part of action effects only.
#' It does not subtract losses unless losses are incorporated elsewhere in the model
#' through additional objectives or constraints.
#'
#' @details
#' This objective can be restricted to subsets of actions and/or features.
#'
#' If \code{actions = NULL}, all actions are included in the objective. If
#' \code{actions} is provided, only rows in \code{x$data$dist_effects} matching that
#' subset of actions contribute to the objective.
#'
#' If \code{features = NULL}, all features are included in the objective. If
#' \code{features} is provided, only rows in \code{x$data$dist_effects} matching that
#' subset of features contribute to the objective.
#'
#' Therefore, the objective can be interpreted as:
#' \deqn{
#' \max \sum_{(pu, action, feature) \in S} benefit_{pu,action,feature}
#' }
#' where \eqn{S} is the subset induced by the selected actions and features. When no
#' subsets are supplied, \eqn{S} includes all feasible rows in \code{dist_effects}.
#'
#' This objective is especially useful when the goal is to prioritize actions that
#' generate gains for particular features or action groups. When trade-offs are important,
#' it is often advisable to combine this objective with explicit treatment of losses
#' elsewhere in the model.
#'
#' @param x A \code{Problem} object.
#' @param actions Optional subset of actions to include in the objective. Values may
#'   match \code{actions$id} and, if present, \code{actions$action_set}. If \code{NULL},
#'   all actions are included.
#' @param features Optional subset of features to include in the objective. Values may
#'   match \code{features$id} and, if present, \code{features$name}. If \code{NULL},
#'   all features are included.
#' @param alias Optional identifier for multi-objective workflows.
#'
#' @return Updated \code{Problem} object.
#'
#' @examples
#' \dontrun{
#' # Maximize total positive effects across all actions and all features
#' p <- add_objective_max_benefit(p)
#'
#' # Maximize positive effects only for a subset of actions
#' p <- add_objective_max_benefit(
#'   p,
#'   actions = c("restoration", "conservation")
#' )
#'
#' # Maximize positive effects only for selected features
#' p <- add_objective_max_benefit(
#'   p,
#'   features = c("sp1", "sp3")
#' )
#'
#' # Restrict the objective to both a subset of actions and a subset of features
#' p <- add_objective_max_benefit(
#'   p,
#'   actions = "restoration",
#'   features = c("sp1", "sp2")
#' )
#' }
#'
#' @export
add_objective_max_benefit <- function(
    x,
    actions = NULL,
    features = NULL,
    alias = NULL
) {
  stopifnot(inherits(x, "Problem"))

  action_subset <- NULL
  feature_subset <- NULL

  if (!is.null(actions)) {
    action_subset <- .pa_resolve_action_subset(x, actions)
  }

  if (!is.null(features)) {
    feature_subset <- .pa_resolve_feature_subset(x, features)
  }

  args <- list(
    actions = if (is.null(action_subset)) NULL else as.integer(action_subset$internal_id),
    features = if (is.null(feature_subset)) NULL else as.integer(feature_subset$internal_id)
  )

  .pa_set_active_and_register_objective(
    x = x,
    model_type = "maximizeBenefits",
    objective_id = "max_benefit",
    objective_args = args,
    sense = "max",
    alias = alias
  )
}

#' @title Add objective: minimize loss
#'
#' @description
#' Specify an objective that minimizes the total negative effects generated by selected
#' actions on selected features.
#'
#' The objective is built from the canonical effects table stored in
#' \code{x$data$dist_effects} and always uses the non-negative \code{loss} component.
#' This objective minimizes the negative part of action effects only. It does not
#' offset losses with benefits unless benefits are handled elsewhere in the model
#' through additional objectives or constraints.
#'
#' @details
#' This objective can optionally be restricted to subsets of actions and/or features.
#'
#' If \code{actions = NULL}, all actions are included. If \code{actions} is provided,
#' only the losses associated with that subset of actions contribute to the objective.
#'
#' If \code{features = NULL}, all features are included. If \code{features} is provided,
#' only the losses associated with that subset of features contribute to the objective.
#'
#' Therefore, this objective minimizes the sum of \code{loss} over the subset of
#' rows in \code{x$data$dist_effects} induced by the selected actions and features.
#'
#' This objective is especially useful when the goal is to avoid damages to particular
#' features or to restrict the harmful effects of particular action groups. When
#' trade-offs are important, it is often advisable to combine this objective with
#' explicit treatment of benefits elsewhere in the model.
#'
#' @param x A \code{Problem} object.
#' @param actions Optional subset of actions to include in the objective. Values may
#'   match \code{actions$id} and, if present, \code{actions$action_set}. If \code{NULL},
#'   all actions are included.
#' @param features Optional subset of features to include in the objective. Values may
#'   match \code{features$id} and, if present, \code{features$name}. If \code{NULL},
#'   all features are included.
#' @param alias Optional identifier for multi-objective workflows.
#'
#' @return Updated \code{Problem} object.
#'
#' @examples
#' \dontrun{
#' # Minimize total losses across all actions and all features
#' p <- add_objective_min_loss(p)
#'
#' # Minimize losses only for a subset of actions
#' p <- add_objective_min_loss(
#'   p,
#'   actions = c("restoration", "harvest")
#' )
#'
#' # Minimize losses only for selected features
#' p <- add_objective_min_loss(
#'   p,
#'   features = c("sp1", "sp3")
#' )
#'
#' # Restrict the objective to both a subset of actions and a subset of features
#' p <- add_objective_min_loss(
#'   p,
#'   actions = "harvest",
#'   features = c("sp1", "sp2")
#' )
#' }
#'
#' @export
add_objective_min_loss <- function(
    x,
    actions = NULL,
    features = NULL,
    alias = NULL
) {
  stopifnot(inherits(x, "Problem"))

  action_subset <- NULL
  feature_subset <- NULL

  if (!is.null(actions)) {
    action_subset <- .pa_resolve_action_subset(x, actions)
  }

  if (!is.null(features)) {
    feature_subset <- .pa_resolve_feature_subset(x, features)
  }

  args <- list(
    actions = if (is.null(action_subset)) NULL else as.integer(action_subset$internal_id),
    features = if (is.null(feature_subset)) NULL else as.integer(feature_subset$internal_id)
  )

  .pa_set_active_and_register_objective(
    x = x,
    model_type = "minimizeLosses",
    objective_id = "min_loss",
    objective_args = args,
    sense = "min",
    alias = alias
  )
}

#' @title Add objective: maximize profit
#'
#' @description
#' Specify an objective that maximizes total profit from selected `(pu, action)` pairs.
#' The objective can optionally be restricted to a subset of actions.
#'
#' @param x A `Problem` object.
#' @param profit_col Character. Profit column in `x$data$dist_profit`.
#' @param actions Optional subset of actions to include. Values may match `actions$id`
#'   and, if present, `actions$action_set`.
#' @param alias Optional identifier for multi-objective workflows.
#'
#' @return Updated `Problem` object.
#' @export
add_objective_max_profit <- function(
    x,
    profit_col = "profit",
    actions = NULL,
    alias = NULL
) {
  stopifnot(inherits(x, "Problem"))

  action_subset <- NULL
  if (!is.null(actions)) {
    action_subset <- .pa_resolve_action_subset(x, actions)
  }

  args <- list(
    profit_col = as.character(profit_col)[1],
    actions = if (is.null(action_subset)) NULL else as.character(action_subset$id)
  )

  .pa_set_active_and_register_objective(
    x = x,
    model_type = "maximizeProfit",
    objective_id = "max_profit",
    objective_args = args,
    sense = "max",
    alias = alias
  )
}

#' @title Add objective: maximize net profit
#'
#' @description
#' Specify an objective that maximizes net profit, optionally restricting the
#' profit and action-cost components to a subset of actions.
#'
#' @param x A `Problem` object.
#' @param profit_col Character. Profit column in `x$data$dist_profit`.
#' @param include_pu_cost Logical. If `TRUE`, subtract planning-unit costs.
#' @param include_action_cost Logical. If `TRUE`, subtract action costs.
#' @param actions Optional subset of actions to include in the profit and action-cost terms.
#'   Values may match `actions$id` and, if present, `actions$action_set`.
#' @param alias Optional identifier for multi-objective workflows.
#'
#' @return Updated `Problem` object.
#' @export
add_objective_max_net_profit <- function(
    x,
    profit_col = "profit",
    include_pu_cost = TRUE,
    include_action_cost = TRUE,
    actions = NULL,
    alias = NULL
) {
  stopifnot(inherits(x, "Problem"))

  action_subset <- NULL
  if (!is.null(actions)) {
    action_subset <- .pa_resolve_action_subset(x, actions)
  }

  args <- list(
    profit_col = as.character(profit_col)[1],
    include_pu_cost = isTRUE(include_pu_cost),
    include_action_cost = isTRUE(include_action_cost),
    actions = if (is.null(action_subset)) NULL else as.character(action_subset$id)
  )

  .pa_set_active_and_register_objective(
    x = x,
    model_type = "maximizeNetProfit",
    objective_id = "max_net_profit",
    objective_args = args,
    sense = "max",
    alias = alias
  )
}

#' @title Add objective: minimize fragmentation
#'
#' @description
#' Specify an objective that minimizes planning-unit fragmentation over a spatial relation.
#'
#' @param x A `Problem` object.
#' @param relation_name Character. Name of the spatial relation.
#' @param weight_multiplier Numeric >= 0. Multiplier applied to relation weights.
#' @param alias Optional identifier for multi-objective workflows.
#'
#' @return Updated `Problem` object.
#' @export
add_objective_min_fragmentation <- function(
    x,
    relation_name = "boundary",
    weight_multiplier = 1,
    alias = NULL
) {
  stopifnot(inherits(x, "Problem"))

  relation_name <- as.character(relation_name)[1]
  weight_multiplier <- as.numeric(weight_multiplier)[1]

  if (!is.finite(weight_multiplier) || weight_multiplier < 0) {
    stop("weight_multiplier must be a finite number >= 0.", call. = FALSE)
  }

  rels <- x$data$spatial_relations
  if (is.null(rels) || !is.list(rels) || is.null(rels[[relation_name]])) {
    stop(
      "Spatial relation '", relation_name, "' not found in x$data$spatial_relations. ",
      "Add it first.",
      call. = FALSE
    )
  }

  args <- list(
    relation_name = relation_name,
    weight_multiplier = weight_multiplier
  )

  .pa_set_active_and_register_objective(
    x = x,
    model_type = "minimizeFragmentation",
    objective_id = "min_fragmentation",
    objective_args = args,
    sense = "min",
    alias = alias
  )
}

#' @title Add objective: minimize action fragmentation
#'
#' @description
#' Specify an objective that minimizes fragmentation at the action level over
#' a spatial relation. The objective can optionally be restricted to a subset
#' of actions and/or weighted by action.
#'
#' @param x A `Problem` object.
#' @param relation_name Character. Name of the spatial relation.
#' @param weight_multiplier Numeric >= 0. Multiplier applied to relation weights.
#' @param action_weights Optional action weights. Either a named numeric vector
#'   (names = action ids) or a `data.frame(action, weight)`.
#' @param actions Optional subset of actions to include. Values may match `actions$id`
#'   and, if present, `actions$action_set`.
#' @param alias Optional identifier for multi-objective workflows.
#'
#' @return Updated `Problem` object.
#' @export
add_objective_min_action_fragmentation <- function(
    x,
    relation_name = "boundary",
    weight_multiplier = 1,
    action_weights = NULL,
    actions = NULL,
    alias = NULL
) {
  stopifnot(inherits(x, "Problem"))

  action_subset <- NULL
  if (!is.null(actions)) {
    action_subset <- .pa_resolve_action_subset(x, actions)
  }

  args <- list(
    relation_name = as.character(relation_name)[1],
    weight_multiplier = as.numeric(weight_multiplier)[1],
    action_weights = action_weights,
    actions = if (is.null(action_subset)) NULL else as.character(action_subset$id)
  )

  .pa_set_active_and_register_objective(
    x = x,
    model_type = "minimizeActionFragmentation",
    objective_id = "min_action_fragmentation",
    objective_args = args,
    sense = "min",
    alias = alias
  )
}


#' @title Add objective: maximize representation
#'
#' @description
#' Specify an objective that maximizes total representation across a subset of features.
#'
#' @param x A `Problem` object.
#' @param amount_col Character. Column in `dist_features` containing amounts.
#' @param features Optional subset of features to include. Values may match
#'   `features$id` and, if present, `features$name`.
#' @param alias Optional identifier for multi-objective workflows.
#'
#' @return Updated `Problem` object.
#' @export
add_objective_max_representation <- function(
    x,
    amount_col = "amount",
    features = NULL,
    alias = NULL
) {
  stopifnot(inherits(x, "Problem"))

  feature_subset <- NULL
  if (!is.null(features)) {
    feature_subset <- .pa_resolve_feature_subset(x, features)
  }

  args <- list(
    amount_col = as.character(amount_col)[1],
    features = if (is.null(feature_subset)) NULL else feature_subset$id
  )

  .pa_set_active_and_register_objective(
    x = x,
    model_type = "maximizeRepresentation",
    objective_id = "max_representation",
    objective_args = args,
    sense = "max",
    alias = alias
  )
}


#' @title Add objective: minimize intervention impact
#'
#' @description
#' Specify an objective that minimizes the impact associated with selecting
#' planning units for intervention. This objective uses planning-unit selection
#' variables (`w`) so that each planning unit contributes at most once,
#' regardless of how many feasible actions exist in that unit.
#'
#' Impact values are taken from the baseline feature distribution in
#' `x$data$dist_features`. Optionally, the objective can be restricted to a
#' subset of features.
#'
#' @param x A `Problem` object.
#' @param impact_col Character. Column in `x$data$dist_features` containing the
#'   per-(pu,feature) impact amount. Default `"amount"`.
#' @param features Optional subset of features to include. Can be feature ids
#'   and, if available, feature names.
#' @param alias Optional alias for multi-objective workflows.
#'
#' @return Updated `Problem` object.
#' @export
add_objective_min_intervention_impact <- function(
    x,
    impact_col = "amount",
    features = NULL,
    actions = NULL,
    alias = NULL
) {
  stopifnot(inherits(x, "Problem"))

  impact_col <- as.character(impact_col)[1]
  if (is.na(impact_col) || !nzchar(impact_col)) {
    stop("impact_col must be a non-empty string.", call. = FALSE)
  }

  if (is.null(x$data$dist_features) ||
      !inherits(x$data$dist_features, "data.frame") ||
      nrow(x$data$dist_features) == 0) {
    stop("x$data$dist_features is missing or empty.", call. = FALSE)
  }

  if (!(impact_col %in% names(x$data$dist_features))) {
    stop(
      "impact_col '", impact_col, "' was not found in x$data$dist_features.",
      call. = FALSE
    )
  }

  feat_subset <- .pa_resolve_feature_subset(x, features = features)
  act_subset  <- .pa_resolve_action_subset(x, subset = actions)

  args <- list(
    impact_col = impact_col,
    features = feat_subset$id,
    actions = act_subset$id
  )

  .pa_set_active_and_register_objective(
    x = x,
    model_type = "minimizeInterventionImpact",
    objective_id = "min_intervention_impact",
    objective_args = args,
    sense = "min",
    alias = alias
  )
}
