#' @include internal.R
NULL

#' @name targets
#' @title Targets API
#'
#' @description
#' Define feature-level targets for a planning problem.
#'
#' Targets are stored in \code{x$data$targets} and later translated into linear
#' constraints when the optimization model is built. They are defined at the
#' feature level, but are evaluated against the total contribution generated by
#' selected actions in the final solution.
#'
#' By default, all actions are allowed to contribute toward target achievement.
#' Optionally, the set of contributing actions can be restricted through the
#' \code{subset} argument.
#'
#' @details
#' Let \eqn{\mathcal{P}} denote the set of planning units, \eqn{\mathcal{A}} the
#' set of actions, and \eqn{\mathcal{F}} the set of features.
#'
#' Let \eqn{x_{ia} \in \{0,1\}} denote whether action \eqn{a \in \mathcal{A}} is
#' selected in planning unit \eqn{i \in \mathcal{P}}.
#'
#' Let \eqn{c_{iaf}} denote the contribution of action \eqn{a} in planning unit
#' \eqn{i} toward feature \eqn{f}, as interpreted by the model from the stored
#' input data.
#'
#' A target for feature \eqn{f} is stored as an absolute threshold
#' \eqn{T_f \ge 0}, together with metadata describing how that threshold was
#' defined. When the optimization model is built, the target is translated into a
#' constraint of the form
#' \deqn{
#' \sum_{(i,a) \in \mathcal{S}_f} c_{iaf} x_{ia} \ge T_f,
#' }
#' where \eqn{\mathcal{S}_f} is the set of planning unit--action pairs allowed to
#' count toward achievement of the target for feature \eqn{f}.
#'
#' By default, \eqn{\mathcal{S}_f} includes all feasible actions. If a
#' \code{subset} is supplied, then \eqn{\mathcal{S}_f} is restricted to the
#' actions matching that subset.
#'
#' \strong{Subset semantics}
#'
#' The \code{subset} argument does \emph{not} change the target value itself. It
#' only determines which actions are allowed to contribute toward target
#' achievement when the model is built.
#'
#' A subset specification may contain:
#' \itemize{
#'   \item action identifiers from \code{x$data$actions$id},
#'   \item action-set labels from \code{x$data$actions$action_set},
#'   \item or a mixture of both.
#' }
#'
#' \strong{Stored fields}
#'
#' Each stored target row contains, at minimum:
#' \describe{
#'   \item{\code{feature}}{Feature identifier.}
#'   \item{\code{sense}}{Constraint direction, currently \code{"ge"}.}
#'   \item{\code{target_unit}}{How the target was defined, for example
#'   \code{"absolute"} or \code{"relative_baseline"}.}
#'   \item{\code{target_raw}}{The user-supplied target value before conversion.}
#'   \item{\code{basis_total}}{The baseline total used when converting a
#'   relative target into an absolute threshold.}
#'   \item{\code{target_value}}{The final absolute threshold stored for model
#'   building.}
#'   \item{\code{subset}}{A text representation of the action subset allowed to
#'   contribute.}
#'   \item{\code{label}}{Optional user label.}
#'   \item{\code{created_at}}{Creation timestamp.}
#' }
#'
#' \strong{Absolute vs relative targets}
#'
#' Absolute targets are stored directly as absolute thresholds:
#' \deqn{
#' T_f = t_f,
#' }
#' where \eqn{t_f} is the value supplied by the user.
#'
#' Relative targets are supplied as proportions \eqn{r_f \in [0,1]} and are
#' converted into absolute thresholds using the current baseline total amount of
#' each feature:
#' \deqn{
#' T_f = r_f \times B_f,
#' }
#' where \eqn{B_f} is the current total amount of feature \eqn{f} in the
#' landscape, computed by \code{.pa_feature_totals()}.
#'
#' \strong{Overwrite behaviour}
#'
#' If \code{overwrite = TRUE}, existing targets for the same feature and subset
#' specification may be replaced. If \code{overwrite = FALSE}, new target rows
#' are appended and any conflict handling is delegated to
#' \code{.pa_store_targets()}.
#'
#' \strong{Input format}
#'
#' The \code{targets} argument is parsed internally by \code{.pa_parse_targets()}
#' and may typically be provided as:
#' \itemize{
#'   \item a single numeric value recycled to all features,
#'   \item a numeric vector aligned to feature order,
#'   \item a named numeric vector where names identify features,
#'   \item a \code{data.frame} with feature identifiers and target values.
#' }
#'
#' @keywords internal
NULL

#' @title Add absolute targets
#'
#' @description
#' Add feature-level absolute targets to a planning problem.
#'
#' These targets are stored in \code{x$data$targets} and later translated into
#' linear constraints when the optimization model is built.
#'
#' Absolute targets are interpreted directly in the same units as the feature
#' contributions used by the model.
#'
#' @details
#' Let \eqn{\mathcal{F}} denote the set of features. For each feature
#' \eqn{f \in \mathcal{F}}, this function stores an absolute target threshold
#' \eqn{T_f \ge 0}.
#'
#' When the optimization model is built, each such target is interpreted as a
#' lower-bound constraint of the form:
#' \deqn{
#' \sum_{(i,a) \in \mathcal{S}_f} c_{iaf} x_{ia} \ge T_f,
#' }
#' where:
#' \itemize{
#'   \item \eqn{x_{ia}} indicates whether action \eqn{a} is selected in planning
#'   unit \eqn{i},
#'   \item \eqn{c_{iaf}} is the contribution of that action to feature
#'   \eqn{f},
#'   \item \eqn{\mathcal{S}_f} is the set of planning unit--action pairs allowed
#'   to count toward the target.
#' }
#'
#' In the absolute case, the stored target threshold is simply:
#' \deqn{
#' T_f = t_f,
#' }
#' where \eqn{t_f} is the user-supplied target value for feature \eqn{f}.
#'
#' The \code{subset} argument restricts which actions may contribute toward
#' achievement of the target, but it does not modify the value of \eqn{T_f}
#' itself.
#'
#' The \code{targets} argument is parsed by \code{.pa_parse_targets()} and may be
#' supplied in several equivalent forms, including:
#' \itemize{
#'   \item a single numeric value recycled to all features,
#'   \item a numeric vector aligned to feature order,
#'   \item a named numeric vector where names identify features,
#'   \item a \code{data.frame} with \code{feature} and \code{target} columns.
#' }
#'
#' Internally, targets added by this function are stored with:
#' \itemize{
#'   \item \code{type = "actions"},
#'   \item \code{sense = "ge"},
#'   \item \code{target_unit = "absolute"},
#'   \item \code{target_raw = target_value},
#'   \item \code{basis_total = NA}.
#' }
#'
#' @param x A \code{Problem} object.
#' @param targets Target specification. This is interpreted as an absolute target
#'   value in the same units as the modelled feature contributions. See Details.
#' @param subset Optional character vector indicating which actions count toward
#'   target achievement. Entries may match action ids, \code{action_set} labels,
#'   or both. If \code{NULL}, all actions count.
#' @param overwrite Logical. If \code{TRUE}, replace existing stored targets for
#'   the same feature and subset combination. If \code{FALSE}, new rows are
#'   appended and overlap handling is delegated to \code{.pa_store_targets()}.
#' @param label Optional character string stored with the targets for reporting
#'   and bookkeeping.
#'
#' @return An updated \code{Problem} object with absolute targets stored in
#'   \code{x$data$targets}.
#'
#' @examples
#' \dontrun{
#' # Same absolute target for all features
#' p <- add_targets_absolute(p, 10)
#'
#' # Different targets by feature id
#' p <- add_targets_absolute(
#'   p,
#'   c("1" = 5, "2" = 8, "3" = 12)
#' )
#'
#' # Only actions in the "recovery" set count toward target achievement
#' p <- add_targets_absolute(
#'   p,
#'   5,
#'   subset = "recovery"
#' )
#'
#' # Mix action sets and specific actions
#' p <- add_targets_absolute(
#'   p,
#'   5,
#'   subset = c("recovery", "conservation_action")
#' )
#' }
#'
#' @seealso
#' \code{\link{add_targets_relative}}
#'
#' @export
add_targets_absolute <- function(x, targets,
                                 subset = NULL,
                                 overwrite = FALSE,
                                 label = NULL) {
  stopifnot(inherits(x, "Problem"))

  x <- .pa_clone_data(x)
  dt <- .pa_parse_targets(x, targets)

  subset_txt <- .pa_subset_to_string(subset)

  out <- data.frame(
    feature      = as.numeric(dt$feature),
    type         = "actions",
    sense        = "ge",
    target_unit  = "absolute",
    target_raw   = as.numeric(dt$target_raw),
    basis_total  = NA_real_,
    target_value = as.numeric(dt$target_raw),
    subset       = subset_txt,
    label        = if (is.null(label)) NA_character_ else as.character(label),
    created_at   = as.character(Sys.time()),
    stringsAsFactors = FALSE
  )

  out <- .pa_add_feature_labels(
    df = out,
    features_df = x$data$features,
    feature_col = "feature",
    internal_feature_col = "internal_feature",
    out_col = "feature_name"
  )

  x$data$meta$model_dirty <- TRUE
  .pa_store_targets(x, out, overwrite = overwrite)
}

#' @title Add relative targets
#'
#' @description
#' Add feature-level relative targets to a planning problem.
#'
#' These targets are stored in \code{x$data$targets} and later translated into
#' linear constraints when the optimization model is built.
#'
#' Relative targets are supplied as proportions in \eqn{[0,1]} and are converted
#' internally into absolute thresholds using the current total amount of each
#' feature in the landscape.
#'
#' @details
#' Let \eqn{\mathcal{F}} denote the set of features. For each feature
#' \eqn{f \in \mathcal{F}}, let \eqn{B_f} denote the current baseline total
#' amount of that feature in the landscape, as computed by
#' \code{.pa_feature_totals()}.
#'
#' If the user supplies a relative target \eqn{r_f \in [0,1]}, then this
#' function converts it to an absolute threshold:
#' \deqn{
#' T_f = r_f \times B_f.
#' }
#'
#' The absolute threshold \eqn{T_f} is stored in \code{target_value}, while:
#' \itemize{
#'   \item the original user-supplied proportion \eqn{r_f} is stored in
#'   \code{target_raw},
#'   \item the baseline total \eqn{B_f} is stored in \code{basis_total}.
#' }
#'
#' When the optimization model is built, the resulting target is interpreted as:
#' \deqn{
#' \sum_{(i,a) \in \mathcal{S}_f} c_{iaf} x_{ia} \ge T_f,
#' }
#' where:
#' \itemize{
#'   \item \eqn{x_{ia}} indicates whether action \eqn{a} is selected in planning
#'   unit \eqn{i},
#'   \item \eqn{c_{iaf}} is the contribution of that action to feature
#'   \eqn{f},
#'   \item \eqn{\mathcal{S}_f} is the set of planning unit--action pairs allowed
#'   to count toward achievement of the target.
#' }
#'
#' The \code{subset} argument restricts which actions may contribute toward
#' target achievement, but it does not affect the baseline amount \eqn{B_f} used
#' to compute the threshold. In other words, relative targets are always scaled
#' against the current full landscape baseline computed by
#' \code{.pa_feature_totals()}.
#'
#' The \code{targets} argument is parsed by \code{.pa_parse_targets()} and may be
#' supplied in several equivalent forms, including:
#' \itemize{
#'   \item a single numeric value recycled to all features,
#'   \item a numeric vector aligned to feature order,
#'   \item a named numeric vector where names identify features,
#'   \item a \code{data.frame} with \code{feature} and \code{target} columns.
#' }
#'
#' Relative targets must lie in \eqn{[0,1]}.
#'
#' Internally, targets added by this function are stored with:
#' \itemize{
#'   \item \code{type = "actions"},
#'   \item \code{sense = "ge"},
#'   \item \code{target_unit = "relative_baseline"},
#'   \item \code{target_raw = r_f},
#'   \item \code{basis_total = B_f},
#'   \item \code{target_value}, equal to \eqn{r_f B_f}.
#' }
#'
#' @param x A \code{Problem} object.
#' @param targets Target specification as proportions in \eqn{[0,1]}. See
#'   Details.
#' @param subset Optional character vector indicating which actions count toward
#'   target achievement. Entries may match action ids, \code{action_set} labels,
#'   or both. If \code{NULL}, all actions count.
#' @param overwrite Logical. If \code{TRUE}, replace existing stored targets for
#'   the same feature and subset combination. If \code{FALSE}, new rows are
#'   appended and overlap handling is delegated to \code{.pa_store_targets()}.
#' @param label Optional character string stored with the targets for reporting
#'   and bookkeeping.
#'
#' @return An updated \code{Problem} object with relative targets stored in
#'   \code{x$data$targets}.
#'
#' @examples
#' \dontrun{
#' # Require 30% of the current baseline total for all features
#' p <- add_targets_relative(p, 0.3)
#'
#' # Require 20% of baseline totals, counting only recovery actions
#' p <- add_targets_relative(
#'   p,
#'   0.2,
#'   subset = "recovery"
#' )
#'
#' # Require 50% of baseline totals, counting a mix of groups and actions
#' p <- add_targets_relative(
#'   p,
#'   0.5,
#'   subset = c("recovery", "conservation_action")
#' )
#' }
#'
#' @seealso
#' \code{\link{add_targets_absolute}}
#'
#' @export
add_targets_relative <- function(x, targets,
                                 subset = NULL,
                                 overwrite = FALSE,
                                 label = NULL) {
  stopifnot(inherits(x, "Problem"))

  x <- .pa_clone_data(x)
  dt <- .pa_parse_targets(x, targets)

  rel <- as.numeric(dt$target_raw)
  if (any(rel < 0 | rel > 1, na.rm = TRUE)) {
    stop("Relative targets must be between 0 and 1.", call. = FALSE)
  }

  basis <- .pa_feature_totals(x)
  basis_v <- basis[as.character(dt$feature)]
  basis_v[is.na(basis_v)] <- 0
  abs_target <- rel * as.numeric(basis_v)

  subset_txt <- .pa_subset_to_string(subset)

  out <- data.frame(
    feature      = as.numeric(dt$feature),
    type         = "actions",
    sense        = "ge",
    target_unit  = "relative_baseline",
    target_raw   = rel,
    basis_total  = as.numeric(basis_v),
    target_value = as.numeric(abs_target),
    subset       = subset_txt,
    label        = if (is.null(label)) NA_character_ else as.character(label),
    created_at   = as.character(Sys.time()),
    stringsAsFactors = FALSE
  )

  out <- .pa_add_feature_labels(
    df = out,
    features_df = x$data$features,
    feature_col = "feature",
    internal_feature_col = "internal_feature",
    out_col = "feature_name"
  )

  x$data$meta$model_dirty <- TRUE
  .pa_store_targets(x, out, overwrite = overwrite)
}
